### ISSUE TITLE
`AccessDenied` Error when trying to download the dataset

### ISSUE THREAD

**Issue by sodabeta7** [sfcompute/tinynarrations#2]
Hi sfcompute,

Thanks for releasing the dataset! I am encountering an access permission issue with aws s3 while trying to download the dataset with `download_data.py`, I didn't really change anything in the script and had my aws credentials ready in `~/.aws/credentials`. 

I'm not sure if this is an issue with my setup, a permissions problem, or something else. Any guidance or suggestions would be greatly appreciated!

**Comment by calculating** [comment]
Hi, sorry about that. We switched to user-pays for egress right before release and forgot to change the download args. New script should fix that, (just added `ExtraArgs={'RequestPayer': 'requester'}` to `s3.download_file`) let me know if it works for you. 

We're swapping in compressed files, but just know that for the splits that are >1tb it's ~$100/tb if you're moving files outside of AWS, so I'd recommend just using the Encodec tokenized files for now (decoding instructions in the readme). Planning to migrate to R2 hosting and a Huggingface dataset interface within a week.

**Comment by sodabeta7** [comment]
thanks for the fix and looking forward to the huggingface dataset!
